// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolCourseRegistration.Data;

namespace SchoolCourseRegistration.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210531193522_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolCourseRegistration.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseNumber")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Cryo 101",
                            CourseNumber = 1101,
                            Credits = 3,
                            Description = "Ice Basics"
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Pyro 101",
                            CourseNumber = 2101,
                            Credits = 5,
                            Description = "Fire Basics"
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Dendro 101",
                            CourseNumber = 3101,
                            Credits = 3,
                            Description = "Tree Basics"
                        });
                });

            modelBuilder.Entity("SchoolCourseRegistration.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "arya@stark.ca",
                            FirstName = "Arya",
                            LastName = "Stark"
                        },
                        new
                        {
                            Id = 2,
                            Email = "dany@drogo.ca",
                            FirstName = "Danaerys",
                            LastName = "Targaryen"
                        },
                        new
                        {
                            Id = 3,
                            Email = "margaery@tyrell.ca",
                            FirstName = "Margaery",
                            LastName = "Tyrell"
                        });
                });

            modelBuilder.Entity("SchoolCourseRegistration.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Registration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1101,
                            InstructorId = 1,
                            RegistrationType = "Part Time",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2101,
                            InstructorId = 2,
                            RegistrationType = "Full Time",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3101,
                            InstructorId = 3,
                            RegistrationType = "Part Time",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2101,
                            InstructorId = 2,
                            RegistrationType = "Full Time",
                            StudentId = 4
                        });
                });

            modelBuilder.Entity("SchoolCourseRegistration.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ted@mosby.ca",
                            FirstName = "Ted",
                            LastName = "Mosby",
                            StudentNumber = 2101
                        },
                        new
                        {
                            Id = 2,
                            Email = "marshall@lawyered.ca",
                            FirstName = "Marshall",
                            LastName = "Eriksen",
                            StudentNumber = 2102
                        },
                        new
                        {
                            Id = 3,
                            Email = "barney@pleas.ca",
                            FirstName = "Barney",
                            LastName = "Stinson",
                            StudentNumber = 2103
                        });
                });

            modelBuilder.Entity("SchoolCourseRegistration.Models.StudentCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StudentCourse");
                });

            modelBuilder.Entity("SchoolCourseRegistration.ViewModel.CourseViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.ToTable("CourseViewModel");
                });

            modelBuilder.Entity("SchoolCourseRegistration.ViewModel.InstructorViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InstructorID")
                        .HasColumnType("int");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorID");

                    b.ToTable("InstructorViewModel");
                });

            modelBuilder.Entity("SchoolCourseRegistration.ViewModel.StudentViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentViewModel");
                });

            modelBuilder.Entity("SchoolCourseRegistration.ViewModel.CourseViewModel", b =>
                {
                    b.HasOne("SchoolCourseRegistration.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID");
                });

            modelBuilder.Entity("SchoolCourseRegistration.ViewModel.InstructorViewModel", b =>
                {
                    b.HasOne("SchoolCourseRegistration.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorID");
                });

            modelBuilder.Entity("SchoolCourseRegistration.ViewModel.StudentViewModel", b =>
                {
                    b.HasOne("SchoolCourseRegistration.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID");
                });
#pragma warning restore 612, 618
        }
    }
}
